
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slankdev
  labels:
    app: slank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slank
  template:
    metadata:
      labels:
        app: slank
    spec:
      hostNetwork: true
      containers:
      - name: slankdev
        image: nginx:1.12
        securityContext:
          privileged: true
        ports:
        - containerPort: 80

